#!/bin/sh

# git stuff
alias ga="git add"
alias gc="git commit"
alias gs="git status"
alias gd="git diff"
alias gr="git restore"
alias glog="git log"
alias gpull="git pull"
alias gpush="git push"
# Rebase master onto current branch
gmrebase() {
    echo "==> Checking out master..."
    git checkout master
    echo ""
    echo "==> Updating master..."
    git pull
    echo ""
    echo "==> Checking back to original branch"
    git checkout -
    echo ""
    echo "==> Rebasing master onto $(git rev-parse --abbrev-ref HEAD)"
    git rebase master $(git rev-parse --abbrev-ref HEAD)
    echo ""
}
# save current work
alias gwip='git add -A; git rm $(git ls-files --deleted) 2> /dev/null; git commit -m "[WIP]: $(date)"'
# Logging helpers
alias gls='git log --pretty=format:"%C(yellow)%h%Cred%d\\ %Creset%s%Cblue\\ [%cn]" --decorate'
alias gll='git log --pretty=format:"%C(yellow)%h%Cred%d\\ %Creset%s%Cblue\\ [%cn]" --decorate --numstat'
alias gdate='git log --pretty=format:"%C(yellow)%h\\ %ad%Cred%d\\ %Creset%s%Cblue\\ [%cn]" --decorate --date=relative'
alias gdatelong='git log --pretty=format:"%C(yellow)%h\\ %ad%Cred%d\\ %Creset%s%Cblue\\ [%cn]" --decorate --date=short'

# config stuff
alias nvimconf="nvim ~/.config/nvim/init.lua"
alias zshconf="nvim ~/.zshrc"
alias awsconf="nvim ~/.config/awesome/rc.lua"
alias aliasconf="nvim ~/.config/aliasrc"
alias vnim="nvim" # I got this typo quit a lot

# exit vim-like
alias :{q,Q}="exit"

alias ls="exa --colour=always --group-directories-first --sort=name"

# nix stuff
alias nixgc="nix-collect-garbage"
alias hm-switch="home-manager switch"
