add_newline = false

[directory]
truncation_length = 8

[git_status]
format = '([\($all_status$ahead_behind\)]($style) )'
ahead = "⇡${count}"
behind = "⇣${count}"
diverged = "⇕⇡${ahead_count} ⇣${behind_count}"

[package]
disabled = true

[golang]
format = "via [ $version](bold blue) "
