[language-server.tinymist]
command = "tinymist"

[language-server.tinymist.config]
preview.background.enabled = true
preview.background.args = ["--data-plane-host=127.0.0.1:9898", "--invert-colors=never"]

[language-server.harper-ls]
command = "harper-ls"
args = [ "--stdio" ]

[language-server.vtsls]
command = "vtsls"
args = [ "--stdio" ]

[language-server.vtsls.config.typescript.inlayHints]
parameterNames.enabled = "literals"
parameterTypes.enabled = true
variableTypes.enabled = true
properlyDeclarationTypes.enabled = true
functionLikeReturnTypes.enabled = true
enummemberValues.enabled = true

[language-server.biome]
command = "biome"
args = ["lsp-proxy"]

# ------------------
 
[[language]]
name = "html"
language-servers = [ "vscode-html-language-server", "tailwindcss-ls" ]

[[language]]
name = "css"
language-servers = [ "vscode-css-language-server", "tailwindcss-ls" ]

[[language]]
name = "typst"
language-servers = ["tinymist", "harper-ls"]
formatter.command = "typstyle"
rulers = [80]
auto-format = true
soft-wrap.enable = true
soft-wrap.wrap-at-text-width = true

[[language]]
name = "markdown"
language-servers = ["harper-ls"]
rulers = [80]
soft-wrap.enable = true
soft-wrap.wrap-at-text-width = true

[[language]]
name = "typescript"
language-servers = [{ name = "vtsls", except-features = ["format"] }, "biome", "tailwindcss-ls"]
formatter = { command = "biome", args = ["format", "--stdin-file-path", "index.astro"] }

[[language]]
name = "javascript"
language-servers = [{ name = "vtsls", except-features = ["format"] }, "biome", "tailwindcss-ls"]
formatter = { command = "biome", args = ["format", "--stdin-file-path", "index.astro"] }

[[language]]
name = "tsx"
language-servers = [{ name = "vtsls", except-features = ["format"] }, "biome", "tailwindcss-ls"]
formatter = { command = "biome", args = ["format", "--stdin-file-path", "index.astro"] }

[[language]]
name = "jsx"
language-servers = [{ name = "vtsls", except-features = ["format"] }, "biome", "tailwindcss-ls"]
formatter = { command = "biome", args = ["format", "--stdin-file-path", "index.astro"] }

[[language]]
name = "astro"
language-servers = [{ name = "astro-ls", except-features = ["format"] }, "biome", "tailwindcss-ls"]
formatter = { command = "biome", args = ["format", "--stdin-file-path", "index.astro"] }
