#!/bin/sh

### BSPWM CONFIGS ### {{{
# Define workspaces
bspc monitor LVDS-1 -d 1 2 3 4 5 6

# border colors
bspc config focused_border_color "#ebdbb2"
bspc config active_border_color "#ebdbb2"
bspc config normal_border_color "#3e3e3e"
bspc config presel_feedback_color "#282828"

bspc config border_width             2
bspc config window_gap               8
bspc config top_padding              28
bspc config bottom_padding           0
bspc config left_padding             0
bspc config right_padding            0

bspc config split_ratio              0.50
bspc config borderless_monocle       true
bspc config gapless_monocle          true
bspc config focus_follows_pointer    true
#}}}

### WINDOW RULES ###{{{

#-----------Class-Name--------------------Workspaces---Focus----Follow------Other Settings-----------------------------#
bspc rule -r *
bspc rule -a Zathura                                  focus=on follow=on state=tiled
bspc rule -a Connman-gtk                              focus=on follow=on state=floating
bspc rule -a Pavucontrol                              focus=on follow=on state=floating
bspc rule -a Pcmanfm                                  focus=on follow=on state=floating
bspc rule -a SimpleScreenRecorder                     focus=on follow=on state=floating
bspc rule -a Sxiv                                     focus=on follow=on state=floating
bspc rule -a Lxappearance                             focus=on follow=on state=floating
bspc rule -a java-lang-Thread                                            state=floating
bspc rule -a Screenkey                     manage=off
bspc rule -a lemonbar                      layer=below
bspc rule -a pop-up                        state=floating
#---------------------------------------------------------------------------------------------------------------------------#}}}

### AUTOSTART ### {{{
killall -9 sxhkd dunst mpd picom lxpolkit
sxhkd &
dunst &
lxpolkit &
clipmenud &
nitrogen --restore &
# lemon_panel &
viper start &
polybar -c ~/.config/polybar/config.ini top &
xsetroot -cursor_name left_ptr &
picom --experimental-backends -b &
xrandr --output LVDS-1 --gamma 0.8:0.8:0.8
setxkbmap -option caps:none
xfce4-power-manager &
(ps x | grep bspswallow | grep -v grep) || bspswallow &
# mpd 2>&1>/dev/null && mpc add / &
# conky &
#}}}

# vim: foldmethod=marker foldlevel=0
