#!/usr/bin/env sh

LINE=0
COUNT=0
LITERAL='<box class="notif-item" orientation="v" spacing="10" space-evenly="false">'

show() {
  ((COUNT+=1))
  OPENED=$(eww windows | grep notification)
  killall -q sleep 2> /dev/null
  echo $LITERAL
  eww update notification=true
  eww update content="$LITERAL"
}

hide() {
  sleep 4.5 && eww update notification=false
}

reset() {
  LITERAL='<box orientation="v" spacing="10" space-evenly="false">'
  COUNT=0
}

build() {
  if [[ $BODY =~ .{50,} ]]; then
    BODY="${BODY:0:50}..."
  fi
  if [[ $SUMMARY =~ .{30,} ]]; then
    SUMMARY="${SUMMARY:0:30}..."
  fi
  if [[ ! -e $APP_ICON && -e /usr/share/icons/Papirus/64x64/mimetypes/$APP_ICON.svg  ]]; then
    APP_ICON=/usr/share/icons/Papirus/64x64/mimetypes/$APP_ICON.svg
    SHOW_ICON=true
  elif [[ -e $APP_ICON ]]; then
    SHOW_ICON=true
  else
    SHOW_ICON=false
  fi
  if [[ $COUNT -gt 4 ]]; then
    reset
  fi
  LITERAL=${LITERAL/%'</box>'}
  LITERAL+="<box orientation=\"v\" space-evenly=\"false\">
    <button>
      <box height=\"80\" spacing=\"0\" orientation=\"h\" space-evenly=\"false\" class=\"foo\">
        <box
          width=\"80\"
          halign=\"center\"
          visible=\"$SHOW_ICON\"
          style=\"background-image: url('$APP_ICON'); border-radius: 5px 0px 0px 5px; background-size:contain; background-position: center; background-repeat: no-repeat\"
        ></box>
        <box
          width=\"200\"
          valign=\"center\"
          space-evenly=\"false\"
          spacing=\"5\"
          orientation=\"v\"
          halign=\"fill\"
          class=\"content\"
        >
          <box
            width=\"230\"
            spacing=\"5\"
            orientation=\"v\"
            valign=\"center\"
            halign=\"start\"
            space-evenly=\"false\"
          >
            <label
              halign=\"start\"
              style=\"color: #84a0c6; font-size: 14px; font-weight: bold\"
              limit-width=\"30\" markup=\"$SUMMARY\"
            />
            <label
              halign=\"start\"
              style=\"color: #6b7089; font-size: 14px;\"
              text=\"$APP_NAME\"
              limit-width=\"15\"
            />
          </box>
          <label
            halign=\"start\"
            valign=\"center\"
            style=\"color: #c6c8d1; margin: 0px; padding: 0px; font-size: 16px\"
            markup=\"$BODY\"
          />
        </box>
      </box>
    </button>
  </box>
</box>"
  show
  hide &
}

tiramisu -s | while read -r value;
do
  if [[ $value =~ \#.* ]]; then
    :
  else
    case $LINE in
      0 )
        if [[ -z $(eww state | grep content | awk '{printf $2}') ]]; then
          reset
        fi
        APP_NAME="${value//\"}"
        ;;
      1 )
        APP_ICON="$value"
        ;;
      3 )
        SUMMARY="${value//\"}"
        ;;
      4 )
        BODY="${value//\"}"
        ;;
      5 )
        ACTION="$value"
        ;;
      8 )
        LINE=-1
        build
        ;;
    esac
  fi
  ((LINE+=1))
done
