import { defineBashFilter } from "./define-filter";

export const xcodebuildFilter = defineBashFilter({
  name: "xcodebuild",
  description: "Compact xcodebuild output — strip build phases, keep errors/warnings/summary",
  matchCommand: new RegExp("^xcodebuild\\b"),
  filters: {
    stripAnsi: true,
    stripLinesMatching: [
      new RegExp("^\\s*$"),
      new RegExp("^CompileC\\s"),
      new RegExp("^CompileSwift\\s"),
      new RegExp("^Ld\\s"),
      new RegExp("^CreateBuildDirectory\\s"),
      new RegExp("^MkDir\\s"),
      new RegExp("^ProcessInfoPlistFile\\s"),
      new RegExp("^CopySwiftLibs\\s"),
      new RegExp("^CodeSign\\s"),
      new RegExp("^Signing Identity:"),
      new RegExp("^RegisterWithLaunchServices"),
      new RegExp("^Validate\\s"),
      new RegExp("^ProcessProductPackaging"),
      new RegExp("^Touch\\s"),
      new RegExp("^LinkStoryboards"),
      new RegExp("^CompileStoryboard"),
      new RegExp("^CompileAssetCatalog"),
      new RegExp("^GenerateDSYMFile"),
      new RegExp("^PhaseScriptExecution"),
      new RegExp("^PBXCp\\s"),
      new RegExp("^SetMode\\s"),
      new RegExp("^SetOwnerAndGroup\\s"),
      new RegExp("^Ditto\\s"),
      new RegExp("^CpResource\\s"),
      new RegExp("^CpHeader\\s"),
      new RegExp("^\\s+cd\\s+/"),
      new RegExp("^\\s+export\\s"),
      new RegExp("^\\s+/Applications/Xcode"),
      new RegExp("^\\s+/usr/bin/"),
      new RegExp("^\\s+builtin-"),
      new RegExp("^note: Using new build system"),
    ],
    maxLines: 60,
    onEmpty: "xcodebuild: ok",
  },
});
