local Color, _, Group = require'colorbuddy'.setup()
local c = require('colorbuddy.color').colors
local g = require('colorbuddy.group').groups
local s = require('colorbuddy.style').styles

local M = {}

M.setup = function(self)
  vim.cmd('hi! clear')

  self:define_colours()
  self:general_colours()
  self:treesitter_colours()
  self:html_colours()
  self:markdown_colours()
  self:diagnostic_colours()
end

M.define_colours = function()
  Color.new('nord0', '#2e3440')
  Color.new('nord1', '#3b4252')
  Color.new('nord2', '#434c5e')
  Color.new('nord3', '#4c566a')

  Color.new('nord4', '#d8dee9')
  Color.new('nord5', '#e5e9f0')
  Color.new('nord6', '#eceff4')

  Color.new('nord7', '#8fbcbb')
  Color.new('nord8', '#88c0d0')
  Color.new('nord9', '#81a1c1')
  Color.new('nord10', '#5e81ac')

  Color.new('nord11', '#bf616a')
  Color.new('nord12', '#d08770')
  Color.new('nord13', '#ebcb8b')
  Color.new('nord14', '#a3be8c')
  Color.new('nord15', '#b48ead')
end

M.general_colours = function()
  Group.new('Normal', c.nord4, c.nord0)
  Group.new('Error', c.nord4, c.nord11, s.bold)
  Group.new('LineNr', c.nord3, nil)
  Group.new('MatchParen', c.nord8, c.nord3)
  Group.new('NonText', c.nord2, nil)
  Group.new('Visual', nil, c.nord2)
  Group.new('VisualNOS', nil, c.nord2)
  Group.new('QuickFixLine', c.nord13, nil)
  Group.new('Terminal', c.nord6, c.nord0)
  Group.new('EndOfBuffer', nil, nil)

  Group.new('ColorColumn', nil, c.nord1)
  Group.new('CursorLine', nil, c.nord1)
  Group.new('Cursor', c.nord0, c.nord4)
  Group.new('CursorLineNr', c.nord4, nil)

  Group.new('Pmenu', c.nord4, c.nord2)
  Group.new('PmenuSbar', c.nord4, c.nord2)
  Group.new('PmenuSel', c.nord3, c.nord8)
  Group.new('WildMenu', c.nord4, c.nord2)

  Group.new('SpecialKey', c.nord3, nil)
  Group.new('SpellBad', c.nord11, nil, s.underline)
  Group.new('SpellCap', c.nord13, nil)
  Group.new('SpellLocal', c.nord5, nil)
  Group.new('SpellRare', c.nord6, nil)

  Group.new('Folded', c.nord3, c.nord0)
  Group.new('FoldColumn', c.nord3, c.nord0)
  Group.new('SignColumn', c.nord1, nil)

  Group.new('Directory', c.nord8, nil)
  Group.new('ErrorMsg', c.nord0, c.nord11)
  Group.new('WarningMsg', c.nord0, c.nord13)
  Group.new('ModeMsg', c.nord4, nil)
  Group.new('MoreMsg', c.nord8, nil)
  Group.new('Question', c.nord4, nil)

  Group.new('Statusline', c.nord6, c.nord3)
  Group.new('StatuslineNC', c.nord4, c.nord3)
  Group.new('StatuslineTerm', c.nord8, c.nord3)
  Group.new('StatuslineTermNC', c.nord4, c.nord3)

  Group.new('TabLine', c.nord4, c.nord1)
  Group.new('TabLineFill', c.nord4, c.nord1)
  Group.new('TabLineSel', c.nord8, c.nord3)

  Group.new('IncSearch', c.nord0, c.nord13)
  Group.new('Search', c.nord0, c.nord9)
  Group.new('Title', c.nord4, nil)
  Group.new('VertSplit', c.nord2, c.nord0)
end

M.syntax_colours = function()
  Group.new('Boolean', c.nord9, nil)
  Group.new('Character', c.nord14, nil)
  Group.new('Comment', c.nord2, nil)
  Group.new('Conditional', c.nord9, nil)
  Group.new('Constant', c.nord8, nil)
  Group.new('Define', c.nord9, nil)
  Group.new('Delimiter', c.nord6, nil)
  Group.new('Exception', c.nord9, nil)
  Group.new('Float', c.nord15, nil)
  Group.new('Function', c.nord8, nil)
  Group.new('Identifier', c.nord4, nil)
  Group.new('Include', c.nord9, nil)
  Group.new('Keyword', c.nord9, nil)
  Group.new('Label', c.nord9, nil)
  Group.new('Number', c.nord15, nil)
  Group.new('Operator', c.nord9, nil)
  Group.new('PreProc', c.nord9, nil)
  Group.new('Repeat', c.nord9, nil)
  Group.new('Special', c.nord10, nil)
  Group.new('SpecialChar', c.nord13, nil)
  Group.new('SpecialComment', c.nord8, nil)
  Group.new('Statement', c.nord15, nil)
  Group.new('StorageClass', c.nord9, nil)
  Group.new('String', c.nord14, nil)
  Group.new('Structure', c.nord13, nil)
  Group.new('Tag', c.nord4, nil)
  Group.new('Todo', c.nord15, nil)
  Group.new('Type', c.nord9, nil)
  Group.new('Typedef', c.nord9, nil)
  Group.new('Macro', c.nord9, nil)
  Group.new('PreCondit', c.nord9, nil)
  Group.new('DiffAdd', c.nord14, nil)
  Group.new('DiffChange', c.nord13, nil)
  Group.new('DiffDelete', c.nord11, nil)
  Group.new('DiffText', c.nord9, nil)
  Group.new('diffAdded', c.nord14, nil)
  Group.new('diffChanged', c.nord13, nil)
  Group.new('diffRemoved', c.nord11, nil)
  Group.new('diffFileId', c.nord10, nil)
  Group.new('diffFile', c.nord1, nil)
  Group.new('diffNewFile', c.nord14, nil)
  Group.new('diffOldFile', c.nord11, nil)
  Group.new('debugPc', c.nord7, nil)
  Group.new('debugBreakpoint', c.nord11, nil)
end

M.treesitter_colours = function()
  Group.new('TSError', g.Error)
  Group.new('TSPunctDelimiter', c.nord9, nil)
  Group.new('TSPunctBracket', c.nord6, nil)
  Group.new('TSPunctSpecial', c.nord6, nil)
  Group.new('TSConstant', g.Constant)
  Group.new('TSConstBuiltin', c.nord9, nil)
  Group.new('TSConstMacro', c.nord9, nil)
  Group.new('TSStringRegex', c.nord14, nil)
  Group.new('TSString', c.nord14, nil)
  Group.new('TSStringEscape', c.nord8)
  Group.new('TSCharacter', c.nord14, nil)
  Group.new('TSNumber', g.Number)
  Group.new('TSBoolean', g.Boolean)
  Group.new('TSFloat', g.Float)
  Group.new('TSAnnotation', c.nord12, nil)
  Group.new('TSAttribute', c.nord7, nil)
  Group.new('TSNamespace', c.nord15, nil)
  Group.new('TSFunction', g.Function)
  Group.new('TSFuncBuiltin', g.Function)
  Group.new('TSFuncMacro', g.Function)
  Group.new('TSParameter', c.nord5, nil)
  Group.new('TSParameterReference', c.nord9, nil)
  Group.new('TSMethod', c.nord8, nil)
  Group.new('TSField', c.nord5, nil)
  Group.new('TSConstructor', c.nord7, nil)
  Group.new('TSConditional', g.Conditional)
  Group.new('TSRepeat', g.Repeat)
  Group.new('TSLabel', g.Label)
  Group.new('TSKeyword', g.Keyword)
  Group.new('TSKeywordFunction', g.Keyword)
  Group.new('TSKeywordOperator', g.Keyword)
  Group.new('TSOperator', g.Operator)
  Group.new('TSException', c.nord9, nil)
  Group.new('TSType', c.nord7, nil)
  Group.new('TSTypeTypeBuiltin', c.nord9, nil)
  Group.new('TSStructure', g.Structure)
  Group.new('TSInclude', g.Include)
  Group.new('TSVariable', c.nord5, nil)
  Group.new('TSVariableBuiltin', c.nord9, nil)
  Group.new('TSText', c.nord4, nil)
  Group.new('TSStrong', c.nord4, nil, s.bold)
  Group.new('TSEmphasis', c.nord4, nil, s.italic)
  Group.new('TSUnderline', nil, nil, s.underline)
  Group.new('TSTitle', g.Title)
  Group.new('TSLiteral', g.String)
  Group.new('TSURI', g.String)
  Group.new('TSTag', c.nord9, nil)
  Group.new('TSTagDelimiter', c.nord10, nil)
end

M.html_colours = function()
  Group.new('htmlArg', c.nord8, nil)
  Group.new('htmlBold', c.nord8, nil, s.bold)
  Group.new('htmlEndTag', c.nord6, nil)
  Group.new('htmlH1', c.nord10, nil, s.bold)
  Group.new('htmlH2', c.nord10, nil, s.bold)
  Group.new('htmlH3', c.nord10, nil, s.bold)
  Group.new('htmlH4', c.nord10, nil, s.bold)
  Group.new('htmlH5', c.nord10, nil, s.bold)
  Group.new('htmlH6', c.nord10, nil, s.bold)
  Group.new('htmlItalic', c.nord15, nil, s.italic)
  Group.new('htmlLink', c.nord7, nil)
  Group.new('htmlSpecialChar', c.nord8, nil)
  Group.new('htmlSpecialTagName', c.nord10, nil)
  Group.new('htmlTag', c.nord10, nil)
  Group.new('htmlTagName', c.nord9, nil)
  Group.new('htmlTitle', g.Title)
end

M.markdown_colours = function()
  Group.new('markdownBlockquote', c.nord3, nil)
  Group.new('markdownBold', c.nord8, nil, s.bold)
  Group.new('markdownCode', c.nord14, nil)
  Group.new('markdownCodeBlock', c.nord14, nil)
  Group.new('markdownCodeDelimiter', c.nord14, nil)
  Group.new('markdownH1', c.nord10, nil, s.bold)
  Group.new('markdownH2', c.nord10, nil, s.bold)
  Group.new('markdownH3', c.nord10, nil, s.bold)
  Group.new('markdownH4', c.nord10, nil, s.bold)
  Group.new('markdownH5', c.nord10, nil, s.bold)
  Group.new('markdownH6', c.nord10, nil, s.bold)
  Group.new('markdownHeadingDelimiter', c.nord11, nil, s.bold)
  Group.new('markdownHeadingRule', c.nord11, nil, s.bold)
  Group.new('markdownId', c.nord15, nil)
  Group.new('markdownIdDeclaration', c.nord10, nil)
  Group.new('markdownIdDelimiter', c.nord15, nil)
  Group.new('markdownItalic', c.nord15, nil, s.italic)
  Group.new('markdownLinkDelimiiter', c.nord15, nil)
  Group.new('markdownLinkText', c.nord10, nil, s.underline)
  Group.new('markdownListMarker', c.nord11, nil)
  Group.new('markdownOrderedListMarker', c.nord11, nil)
  Group.new('markdownRule', c.nord10, nil)
  Group.new('markdownUrl', c.nord7, nil, s.underline)
end

M.diagnostic_colours = function()
  Group.new('LspDiagnosticsWarning', c.nord13, nil)
  Group.new('LspDiagnosticsDefaultError', c.nord11, nil)
  Group.new('LspDiagnosticsInformation', c.nord8, nil)
  Group.new('LspDiagnosticsHint', c.nord10, nil)
  Group.new('LspDiagnosticsUnderlineWarning', c.nord13, nil, s.underline)
  Group.new('LspDiagnosticsUnderlineError', c.nord11, nil, s.underline)
  Group.new('LspDiagnosticsUnderlineInformation', c.nord8, nil, s.underline)
  Group.new('LspDiagnosticsUnderlineHint', c.nord10, nil, s.underline)
end

return M
