#!/bin/sh

nitrogen --restore &                          # restore wallpaper
dunst &                                       # notification daemon
lxpolkit &                                    # policy kit
clipmenud &                                   # dmenu based clipboard manager
xfce4-power-manager &                         # battery power manager
xset r rate 300 50 &                          # gotta go fast
# polybar -c ~/.config/polybar/config.ini top &
tint2 -c ~/.config/tint2/leve-orange.tint2rc &
picom --experimental-backends -b &            # compositor to prevent screen tearing
xrandr --output LVDS-1 --gamma 0.8:0.8:0.8    # set screen gamma to be a bit darker
setxkbmap -option caps:none                   # capslock sucks
# mpd 2>&1>/dev/null && mpc add / &             # start music player daemon, gotta get dem musics

# xinput set-prop 10 "Device Enabled" 0 &
# xmodmap -e "keycode 135 = Super_L" &

# xsetroot -cursor left_ptr &                   # set cursor shape
# ~/.config/polybar/launch.sh start &           # start polybar
