# Environmental variables
# export NPM_CONFIG_PREFIX=$HOME/.local/npm
export EDITOR="/usr/bin/nvim"
export DOTS="/home/elianiva/repos/dotfiles"
export TERMINAL="/usr/bin/alacritty"
export CM_LAUNCHER="rofi"
export QT_QPA_PLATFORMTHEME="qt5ct"
export QT_AUTO_SCREEN_SCALE_FACTOR=0
export GTK2_RC_FILES="$HOME/.gtkrc-2.0"
export PATH="$(du "$HOME/.scripts" | cut -f2 | tr '\n' ':' | sed 's/:*$//'):$HOME/.local/bin:$HOME/.gem/ruby/2.7.0/bin:$HOME/.local/npm/bin:$HOME/.config/composer/vendor/bin:$HOME/go/bin:$HOME/.pub-cache/bin:$PATH"

# Tidy up stuff
export LESSHISTFILE="${XDG_CONFIG_HOME}less/history"
export LESSKEY="${XDG_CONFIG_HOME}less/keys"
export ICEAUTHORITY=${XDG_CACHE_HOME}ICEauthority
export ZIM_HOME="${HOME}/.zim"

export LF_ICONS="di= :\
fi= :\
tw= :\
ow= :\
ln= :\
or= :\
ex= :\
*.txt=✍:\
*.mom=✍:\
*.me=✍:\
*.ms=✍:\
*.png= :\
*.webp= :\
*.ico= :\
*.jpg= :\
*.jpe= :\
*.jpeg= :\
*.gif=🖼:\
*.svg=🗺:\
*.tif=🖼:\
*.tiff=🖼 :\
*.xcf=🖌:\
*.html=🌎 :\
*.xml= :\
*.gpg=🔒:\
*.css= :\
*.pdf=📚:\
*.djvu=📚:\
*.epub=📚:\
*.csv= :\
*.xlsx= :\
*.tex= :\
*.md= :\
*.r=📊:\
*.R=📊:\
*.rmd=📊:\
*.Rmd=📊:\
*.m=📊:\
*.mp3= :\
*.opus= :\
*.ogg= :\
*.m4a= :\
*.flac= :\
*.mkv=辶:\
*.mp4=辶:\
*.webm=辶:\
*.mpeg=辶:\
*.avi=辶:\
*.zip=遲:\
*.rar=遲:\
*.7z=遲:\
*.tar.gz= :\
*.z64=🎮:\
*.v64=🎮:\
*.n64=🎮:\
*.gba=🎮:\
*.nes=🎮:\
*.gdi=🎮:\
*.1=ℹ:\
*.nfo=ℹ:\
*.info=ℹ:\
*.log=📚:\
*.iso= :\
*.img= :\
*.bib=🎓:\
*.ged=👪:\
*.part=💔:\
*.torrent= :\
*.jar=♨:\
*.java=♨:\
"
